### PR TITLE
fixed code generation for Iterate corner cases

### PR DESCRIPTION
**Pull request by jjthomas**
@mateiz can you take a look, your `iterate_with_parallel_body` is basically a test for this (it won't pass anymore without the change to `sir_param_correction_helper`

### CODE REVIEW

**Comment by jjthomas** [comment]
never mind, updated `iterate_with_parallel_body` so that it fails without this change

**Comment by mateiz** [comment]
Seems OK, but can you make sure it's not adding more parameters to the closure than needed in other cases? I guess that in normal cases, those have unique IDs? It would be nice to directly test sir_param_correction actually -- just make a few cases and see what it does.

**Comment by jjthomas** [comment]
It definitely can't add more params to the closure that needed because anything that's already in the params list of a called function must be passed in by its caller, so we are safe there. I can add tests for `sir_param_correction` if you want.

**Comment by mateiz** [comment]
OK, this fix seems fine but it would be good to add a full test to this that just creates a SIR program and then runs this (or even that goes from AST to SIR).

**Pull request merged**
