### PR TITLE
uniquifier bugfix & better iterate codegen to reduce extraneous params

### PR DESCRIPTION
**Pull request by jjthomas**
@sppalkia check the uniquifier fix and see if it looks good

### CODE REVIEW

**Comment by jjthomas** [comment]
actually hold off on merging this, i am going to make the tests a little better

**Comment by jjthomas** [comment]
@sppalkia @mateiz take a look at this now, the new tests actually didn't really test anything interesting so i removed them

**Comment by mateiz** [comment]
Wait so what is this fixing then? Can't we add a test that reproduces the problem?

**Comment by jjthomas** [comment]
@mateiz pushed a test that breaks without the uniquifier fix, the other change to sir.rs just improves the generated code so it doesn't pass around unneeded params, so there's not a test for it

**Comment by mateiz** [comment]
Awesome, thanks!

**Pull request merged**
