### PR TITLE
Predicate only when annotation is true

### PR DESCRIPTION
**Pull request by pratiksha**
Plus, refactoring to add annotations to If and For exprs.

This change means predication will never be applied to code that doesn't have the annotation -- I don't think this breaks backwards-compatibility since predication is turned off by default anyway, but let me know.

### CODE REVIEW

**Comment by deepakn94** [comment]
Looks good to me.
Can you also add an end-to-end test similar to [this](https://github.com/weld-project/weld/blob/master/tests/integration_tests.rs#L880), but with an `if` condition that both has and doesn't have the `predicate` annotation?

**Comment by pratiksha** [comment]
@deepakn94 ptal

**Comment by deepakn94** [comment]
LGTM, ship it! (Use the `squash and merge` option)

**Comment by deepakn94** [comment]
(Wait for tests on Travis to pass first)

**Pull request merged**
