### PR TITLE
Simplify the way WeldError parameter passed in

### PR DESCRIPTION
**Pull request by viirya**
The way that `WeldError` parameter passed to `weld_module_compile` and `weld_module_run` looks obscure for now.

This is going to simplify it.

### CODE REVIEW

**Comment by deepakn94** [comment]
Hi @viirya,
Can you please fix the breaking tests? (you can run locally using `cargo test`)
Thanks!
Deepak

**Comment by viirya** [comment]
@deepakn94 I've fixed the tests. Please take a look again. Thanks.

**Comment by viirya** [comment]
ping @deepakn94

**Comment by sppalkia** [comment]
Hi @viirya,

There's a few places where this API update needs to be reflected. Can you update the following files accordingly (unfortunately these things aren't tested by the CI system yet, but they will be soon):

* `./examples/cpp/add_repl/add_repl.cpp` (use `weld_error_new` instead of `NULL`)
* `./docs/api.md` (add the new API call here)
* `./c/weld.h` (add the new API call here)
* `./benches/benches.rs` (update this in the same manner you updated `integration_tests.rs`; you can test it using `cargo bench`).

Thanks!

**Comment by viirya** [comment]
@sppalkia Thanks for pointing out the necessary changes! I've done the changes. Please take a look and let me know if anything else is needed. Thanks!

**Comment by sppalkia** [comment]
Hi @viirya,

This looks good! I'll go ahead and merge this in.

Thank you for contributing to the project! If you have any suggestions or comments, feel free to share your thoughts on the [Google Group](https://groups.google.com/forum/#!forum/weld-users).

**Comment by viirya** [comment]
@sppalkia @deepakn94 Thanks for review!

**Pull request merged**
